fix(ui): show popup variation rule message while hovering on variation delete button
bucketeer-io/bucketeer pull request #143
Opened 2022-12-30 08:24 UTC by bimalgrg519

…n delete button

2022-12-31 11:09 UTC, cre8ivejp commented
Thank you for your PR!

I deployed it and found a bug when the same variation is being used in the default and off variation. It shows the HoverPopover without a message.

![Screen Shot 2022-12-31 at 19 57 53](https://user-images.githubusercontent.com/2486691/210134488-5d6823d9-e8da-4831-93c3-ac5468673949.png)

It will be easier to understand and simple if we don't show the delete button when there are only two variations. What do you think?
Also, can you limit the popover's width to 350px?

2023-01-01 09:33 UTC, bimalgrg519 commented
When there are only two variations and lets say no rule being applied on second variation then we can hide delete button on second variation right?

2023-01-01 09:40 UTC, cre8ivejp commented
@bimalgrg519 

> When there are only two variations and lets say no rule being applied on second variation then we can hide delete button on second variation right?

No. If we have only two variations, there is no need to check if there is a rule to the second variation.
We check the list length, and if it is two, we hide the delete button.
If we have three or more variations, then we show the delete buttons using the conditions that you implemented in the PR.

2023-01-01 09:59 UTC, bimalgrg519 commented
Thank you for the explanation. Sent PR.

2023-01-01 10:10 UTC, cre8ivejp commented
@bimalgrg519 

I found that when you have four variations and delete variation 1, it doesn't update the delete button status. Can you take a look, please?
http://localhost:8000/development/features/feature-flag-string/variation

Added four variations
![Screen Shot 2023-01-01 at 19 03 59](https://user-images.githubusercontent.com/2486691/210167137-d8ee5aaa-e6df-4f74-a1cb-e2e513e12fce.png)

After you removed variation 1.
![Screen Shot 2023-01-01 at 19 04 11](https://user-images.githubusercontent.com/2486691/210167177-2bd8cb0e-3366-404d-9bb1-a3e444ca66d1.png)

2023-01-06 02:59 UTC, cre8ivejp requested changes

2023-01-06 04:05 UTC, cre8ivejp commented on ui/web-v2/apps/admin/src/components/VariationInput/index.tsx
> +          // Check if the variation is both the on and off variation
nit: `Check if the variation is both on and off variations`

2023-01-06 04:05 UTC, cre8ivejp commented on ui/web-v2/apps/admin/src/components/VariationInput/index.tsx
> +          // Check if the variation is both the on and off variations
nit: `Check if the variation is both on and off variations`

2023-01-06 04:11 UTC, cre8ivejp commented on ui/web-v2/apps/admin/src/components/VariationInput/index.tsx
> +          // Check if the variation is both on and off variation
nit: `Check if the variation is both on and off variations`

2023-01-06 04:33 UTC, cre8ivejp approved these changes
Thank you!!!

2023-01-06 04:33 UTC, merged