chore: add codeNoLink metrics to dwh
bucketeer-io/bucketeer pull request #191
Opened 2023-01-26 09:30 UTC by ono-max

2023-01-26 10:02 UTC, cre8ivejp requested changes

2023-01-26 10:02 UTC, cre8ivejp commented on pkg/eventpersisterdwh/persister/evaluation_event.go
> +					handledCounter.WithLabelValues(codeNoLink).Inc()
Can you also add `Linked` metrics?

E.g.
https://github.com/bucketeer-io/bucketeer/blob/main/pkg/eventpersisterops/persister/evaluation_event.go#L90
https://github.com/bucketeer-io/bucketeer/blob/main/pkg/eventpersisterops/persister/goal_event.go#L97

2023-01-26 10:14 UTC, ono-max commented
@cre8ivejp 

Thank you. I've updated.

2023-01-26 10:47 UTC, masaaania approved these changes
LGTM!

2023-01-30 02:05 UTC, cre8ivejp approved these changes
Good good!

2023-01-30 02:36 UTC, merged