chore: store evaluation count in redis
bucketeer-io/bucketeer pull request #91
Opened 2022-12-05 05:11 UTC by ono-max

2022-12-05 08:30 UTC, cre8ivejp requested changes

2022-12-05 08:30 UTC, cre8ivejp commented on pkg/eventpersister/persister/persister.go
> +func (p *Persister) key(kind, featureID, variationID string, timestamp int64) string {
Sorry for mentioning this now, but we also need the `environmentNamespace` in the key.

- Event count: `ec:environment_namespace:feature_flag_id:variation_id:daily_timestamp`
- User count: `uc:environment_namespace:feature_flag_id:variation_id:daily_timestamp`

2022-12-05 08:30 UTC, cre8ivejp commented on pkg/cache/cache.go
> +	PFAdd(key string, els []string) (int64, error)
We should change the interface to:

E.g. `PFAdd(key string, els ...string) (int64, error)`

Also in here:
https://github.com/bucketeer-io/bucketeer/blob/main/pkg/redis/v3/redis.go#L66

Reference:
https://pkg.go.dev/github.com/fiorix/go-redis/redis#Client.PFAdd

2022-12-05 09:56 UTC, ono-max commented
@cre8ivejp 

I've updated 👍

2022-12-06 07:35 UTC, masaaania approved these changes
LGTM!

2022-12-06 07:39 UTC, cre8ivejp approved these changes
Nice!
Thanks!

2022-12-06 07:40 UTC, merged